### ISSUE TITLE
open source + launch checklist

### ISSUE THREAD

**Issue by aymannadeem** [aymannadeem/yourhaq#7]
#### Must-haves
- [x] README
- [ ] roadmap (concrete suggestions)
- [x] Facebook group
- [x] Twitter account
- [x] Facebook messaging content
- [x] Add FB/Twitter links

#### Nice-to-haves
- [ ] issue template 
- [ ] rebase history

**Comment by dmleong** [comment]
I strongly encourage adding a [Code of Conduct](http://contributor-covenant.org/version/1/4/) to this early on

**Comment by hectorsector** [comment]
> roadmap (concrete suggestion

Regarding the roadmap, it seems that the following items from https://github.com/aymannadeem/yourhaq/issues/10 would be a good fit for a roadmap starting place:

> Filter based on status: Allow users to choose their status (ie., "refugee", "green card holder", "TN visa holder", "US citizen", "undocumented", etc.) and filter search results based on that (and possibly location?)

> Legal information submission form: Currently, all information is to be submitted on the linked GitHub repository using Issues (if lawyers/legal experts want to submit information, they open an issue detailing their ideas and information). This isn't as accessible as a contact form on the site.

**Comment by aymannadeem** [comment]
Now that we're up and running closing this and driving roadmap in #24. Thanks for input here @dmleong and @hectorsector! ✨
